### ISSUE TITLE
Attributes not being read

### ISSUE THREAD

**Issue by Brezenabsalzer** [acampb311/xml2struct#3]
Hi,
I encountered a problem when reading a XML File with node attributes. The according data is not imported whereas this function https://de.mathworks.com/matlabcentral/fileexchange/28518-xml2struct is able to import the info. I attached an example to show the problem that the info from <triggerduration> is missing when using the mex function.
[test.zip](https://github.com/acampb311/xml2struct/files/3107535/test.zip)
Many thanks!

**Comment by acampb311** [comment]
hey @Brezenabsalzer, I took a look at this, seems there was an edge case where a node with no children wouldn't go through the process of checking if it had attributes. 
The struct file generated from the test.xml you provided now matches between this xml2struct and the matlab one from the fileexchange. Hope this helps. 

https://github.com/acampb311/xml2struct/blob/7583bd46de56e0bf8b948bd453a0d61c67968a85/xml2struct.cpp#L104-L106

**Comment by Brezenabsalzer** [comment]
Perfect! Thank you very much!
